name: CI Workflow

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Compile the application
    - name: Compile
      run: npm install && npm run build

    # Run Linters
    - name: Run Linters
      run: npm run lint

    # Run Tests
    - name: Run Tests
      run: npm test

    # Build Docker Image
    - name: Build Docker Image
      run: docker build -t myapp:latest .

    # Login to Docker Registry
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push Docker Image
    - name: Push Docker Image
      run: docker push myapp:latest
